# Generated by Django 2.2.5 on 2019-11-11 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accountant',
            fields=[
                ('ano', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('dno', models.CharField(max_length=8)),
                ('aname', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'accountant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('ano', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('cno', models.CharField(max_length=8)),
                ('ino', models.CharField(max_length=8)),
                ('sum', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'amount',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField()),
                ('permission_id', models.IntegerField()),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content_type_id', models.IntegerField()),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('group_id', models.IntegerField()),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('permission_id', models.IntegerField()),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Creditofficer',
            fields=[
                ('cono', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('coname', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=2)),
                ('dname', models.CharField(max_length=20)),
                ('tel', models.IntegerField()),
            ],
            options={
                'db_table': 'creditofficer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cno', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=20)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('sex', models.CharField(max_length=2)),
                ('c_addr', models.CharField(blank=True, max_length=20, null=True)),
                ('money', models.BigIntegerField(blank=True, null=True)),
                ('idcard', models.CharField(max_length=18)),
                ('is_loan', models.CharField(max_length=2)),
                ('level', models.CharField(max_length=2)),
                ('dno', models.CharField(max_length=8)),
                ('lno', models.CharField(max_length=8)),
                ('ino', models.CharField(max_length=8)),
                ('cono', models.CharField(max_length=8)),
                ('eap', models.CharField(max_length=8)),
                ('loanmoney', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dno', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('dname', models.CharField(max_length=20)),
                ('tel', models.CharField(blank=True, max_length=11, null=True)),
                ('d_addr', models.CharField(max_length=20)),
                ('person_in_charge', models.CharField(max_length=20)),
                ('apno', models.CharField(max_length=8)),
                ('aptime', models.CharField(max_length=20)),
                ('cno', models.CharField(max_length=8)),
                ('approver', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
                ('content_type_id', models.IntegerField(blank=True, null=True)),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('ino', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('cno', models.CharField(max_length=8)),
                ('rate', models.FloatField()),
                ('is_deal', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'interest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('lno', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('cno', models.CharField(max_length=8)),
                ('ino', models.CharField(max_length=8)),
                ('kind', models.CharField(max_length=20)),
                ('money', models.CharField(max_length=20)),
                ('foreclosure', models.CharField(max_length=20)),
                ('limittime', models.CharField(max_length=20)),
                ('recycle', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'loan',
                'managed': False,
            },
        ),
    ]
