from django.conf.urls import url
from . import views

app_name = 'loan'
urlpatterns = [
    url(r'^$',views.home),
    url('home/', views.home, name='home'),
    url('login/', views.login, name='login'),
    url('register/', views.register, name='register'),
    url('personal/', views.personal, name='personal'),
    url('certification/', views.certification, name='certification'),
    url('myLoan/', views.myLoan, name='myLoan'),
    url('apply/', views.apply, name='apply'),
    url('loans/', views.loans, name='loans'),
    url('aboutus/', views.aboutus, name='aboutus'),
    url('connect/', views.connect, name='connect'),
    url('company/', views.company, name='company'),
    url('service/', views.service, name='company'),
    url('loginPost/', views.loginPost, name='loginPost'),
    url('signupPost/', views.signupPost, name='signupPost'),
    url('sendMail/', views.sendMail, name='sendMail'),
    url('certify/', views.certify, name='certify'),
    url('applyForm/', views.applyForm, name='applyForm'),
    url('personalPost/', views.personalPost, name='personalPost'),
    url('sendCertification/', views.sendCertification, name='sendCertification'),
    url('logoutPost/', views.logoutPost, name='logoutPost'),
    # 后台
    url('loanManage/', views.loanManage, name='loanManage'),
    url('creditRankPost/', views.creditRankPost, name='creditRankPost'),
    url('loanPost/', views.loanPost, name='loanPost'),
    url('backPost/', views.backPost, name='backPost'),
    url('personnelDelPost/', views.personnelDelPost, name='personnelDelPost'),
    url('loanDetails/', views.loanDetails, name='loanDetails'),
    url('loanDetails2/', views.loanDetails2, name='loanDetails2'),
    url('loanApproval/', views.loanApproval, name='loanApproval'),
    url('loanApprovalDatas/',views.loanApprovalDatas,name='loanApprovalDatas'),
    url('backLogoutPost/',views.backLogoutPost,name='backLogoutPost'),
    url('personnelManage/', views.personnelManage, name='personnelManage'),
    url('personnelEdit/', views.personnelEdit, name='personnelEdit'),
    url('personnelAdd/', views.personnelAdd, name='personnelAdd'),
    url('loanApprovalDetails/', views.loanApprovalDetails, name='loanApprovalDetails'),
    url('loanDetailsPost/', views.loanDetailsPost, name='loanDetailsPost'),
    url('addloanPost/', views.addloanPost, name='addloanPost'),
    url('personnelEditPost/', views.personnelEditPost, name='personnelEditPost'),
    url('personnelAddPost/', views.personnelAddPost, name='personnelAddPost'),
    url('backstageLogin/', views.backstageLogin, name='backstageLogin'),
    #url('', views.home, name='home'),
    url('sidebar/', views.sidebar, name='sidebar'),
    url('applyFirst/', views.applyFirst, name='applyFirst'),
    url('applyFiles/',views.applyFiles,name='applyFiles'),
    url('credit/',views.credit,name='credit'),
    url('error404/',views.page_not_found,name='page_error'),
    url('error500/',views.page_error,name='page_error'),
]

